#!/bin/bash
sudo apt-get update
sudo apt-get upgrade

#mongoDB
curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
   --dearmor

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

#fish
sudo apt-add-repository ppa:fish-shell/release-2

sudo apt-get install -y unzip nginx gnupg curl git build-essential mongodb-org nodejs fish npm
sudo systemctl enable mongod.service

sudo npm install -g pm2
sudo npm install -g nodemon

#set fish as default shell
chsh -s /usr/bin/fish
