#!/bin/bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y terminator unzip nginx curl git build-essential

#nodeJS
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

#mongoDB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

#fish
sudo apt-add-repository ppa:fish-shell/release-2

sudo apt-get update
sudo apt-get install -y mongodb-org nodejs fish

sudo npm install grunt-cli -g
sudo npm install -g pm2
sudo npm install -g nodemon

#set fish as default shell
chsh -s /usr/bin/fish
