#!/bin/bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y terminator unzip apache2 libapache2-mod-proxy-html libxml2-dev curl git

#instala os modulos de proxy do apache
sudo a2enmod proxy proxy_http proxy_ajp rewrite deflate headers proxy_balancer proxy_connect proxy_html

#nodeJS
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

#mongoDB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

#fish
sudo apt-add-repository ppa:fish-shell/release-2

sudo apt-get update
sudo apt-get install -y mongodb-org nodejs fish

#Vhost
git clone https://github.com/rubensfernandes/vhost-manager.git
cd vhost-manager
sudo chmod +x vhost
sudo ./vhost -install

sudo npm install grunt-cli -g
sudo npm install -g pm2

#set fish as default shell
chsh -s /usr/bin/fish
